// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    nfhs_district_health_indicators: {
        name: "nfhs_district_health_indicators";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          districtName: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType BIGINT */
          householdsSurveyed: number;
          /** @sqlType BIGINT */
          womenInterviewed: number;
          /** @sqlType BIGINT */
          menInterviewed: number;
          /** @sqlType DOUBLE */
          improvedWaterPct: number;
          /** @sqlType DOUBLE */
          improvedSanitationPct: number;
          /** @sqlType DOUBLE */
          cleanFuelPct: number;
          /** @sqlType DOUBLE */
          healthInsurancePct: number;
          /** @sqlType DOUBLE */
          womenLiteracyPct: number;
          /** @sqlType DOUBLE */
          institutionalBirthPct: number;
          /** @sqlType DOUBLE */
          skilledBirthAttendancePct: number;
          /** @sqlType DOUBLE */
          cSectionPct: number;
          /** @sqlType DOUBLE */
          childStuntedPct: number;
          /** @sqlType DOUBLE */
          childWastedPct: number;
          /** @sqlType DOUBLE */
          childUnderweightPct: number;
          /** @sqlType DOUBLE */
          womenAnaemiaPct: number;
          /** @sqlType DOUBLE */
          womenHighBpPct: number;
          /** @sqlType DOUBLE */
          menHighBpPct: number;
        }>;
      };
  }
}
